{"name": "Checking the number of main menu items", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Locator.fill: Timeout 30000ms exceeded.\nCall log:\nwaiting for locator(\"#username\")", "trace": "page = <Page url='about:blank'>\n\n    @allure.severity(allure.severity_level.NORMAL)\n    @allure.feature(\"Dashbord page\")\n    @allure.title(\"Checking the number of main menu items\")\n    \n    def test_main_menu(page):\n        dash_page = LoginPage(page)\n>       dash_page.login(\"admin\", \"admin\")\n\ntest_dashbord_page.py:15: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n../pages/login_page.py:17: in login\n    self.user_name.fill(username)\n../../my_venv/lib/python3.9/site-packages/playwright/sync_api/_generated.py:15276: in fill\n    self._sync(\n../../my_venv/lib/python3.9/site-packages/playwright/_impl/_locator.py:208: in fill\n    return await self._frame.fill(self._selector, strict=True, **params)\n../../my_venv/lib/python3.9/site-packages/playwright/_impl/_frame.py:527: in fill\n    await self._channel.send(\"fill\", locals_to_params(locals()))\n../../my_venv/lib/python3.9/site-packages/playwright/_impl/_connection.py:59: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <playwright._impl._connection.Connection object at 0x7fd5932d5670>\ncb = <function Channel.send.<locals>.<lambda> at 0x7fd593677a60>, is_internal = False\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(task, \"__pw_stack__\", inspect.stack())\n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.TimeoutError: Locator.fill: Timeout 30000ms exceeded.\nE           Call log:\nE           waiting for locator(\"#username\")\n\n../../my_venv/lib/python3.9/site-packages/playwright/_impl/_connection.py:514: TimeoutError"}, "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1721167763357, "stop": 1721167793380, "uuid": "60a0ce5c-9b59-4c94-bccf-8eb8c8cb8966", "historyId": "321b63ac9bc4e68e3a62d26704f786dc", "testCaseId": "858e0530d952b93d85b1417b6126be3b", "fullName": "tests.test_dashbord_page#test_main_menu", "labels": [{"name": "feature", "value": "Dashbord page"}, {"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_dashbord_page"}, {"name": "host", "value": "Air-Mihail.attlocal.net"}, {"name": "thread", "value": "19484-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_dashbord_page"}]}